### ISSUE TITLE
Adding embargoed work to a collection throws SWW

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#138]
When I added an embargoed work to a collection, I get a rails error "Something went wrong". 

1. Navigate to an existing collection
2. add existing embargoed work
3. click save changes

SWW.

Seems to work for public and private. 

![screen shot 2017-12-01 at 4 15 06 pm](https://user-images.githubusercontent.com/4356335/33503767-f70dfee8-d6b2-11e7-8461-61a8d888afe9.png)
![screen shot 2017-12-01 at 4 15 15 pm](https://user-images.githubusercontent.com/4356335/33503769-f9b00f60-d6b2-11e7-9d2f-c0cf9de579da.png)
![screen shot 2017-12-01 at 4 15 23 pm](https://user-images.githubusercontent.com/4356335/33503774-ff3164f2-d6b2-11e7-864a-38e6a4dd340a.png)

**Comment by elrayle** [comment]
The message in the log...
```
ActiveFedora::RecordInvalid (Validation failed: Embargo release date Must be a future date):
active-fedora (11.5.2) lib/active_fedora/validations.rb:89:in `raise_validation_error'
lib/active_fedora/validations.rb:56:in `save!
lib/active_fedora/associations/builder/orders.rb:50:in `save!'
app/models/concerns/hyrax/collection_behavior.rb:70:in `block in add_member_objects'
app/models/concerns/hyrax/collection_behavior.rb:61:in `each'
app/models/concerns/hyrax/collection_behavior.rb:61:in `add_member_objects'
app/controllers/hyrax/dashboard/collections_controller.rb:405:in `add_members_to_collection'
app/controllers/hyrax/dashboard/collections_controller.rb:397:in `process_member_changes'
app/controllers/hyrax/dashboard/collections_controller.rb:153:in `update'
```

The work I selected has an Embargo release date of 10/30/2017

What is supposed to happen to an embargoed work when its release date passes?  Perhaps the work is in an improper state.

**Comment by elrayle** [comment]
I created a new embargoed work with a date that was clearly in the future and was able to add it as an existing work to a collection following the steps in this issue.

**Comment by julesies** [comment]
@elrayle you have to manually release works from embargo and hide works that have expired leases. Strange it would care when adding to a collection? Were you able to add an embargoed work that is within date range? I will try that tomorrow and will expire an embargo and test that too.

**Comment by elrayle** [comment]
@jrr I was able to add an embargoed work where the release date is in the future.

**Comment by julesies** [comment]
Just saw your previous comment re a work with a current embargo

**Comment by julesies** [comment]
Will try to expire the embargo tomorrow and make sure it can be added.

**Comment by elrayle** [comment]
@jrr I tested this with an embargo with a future release date and it was added.  I tested again with an embargo with an expired release date and got SWW.

What is happening is that when you add a work to a collection, the relationship is put on the work to know about its parent collection.  So this requires a save of the work.  Embargo requires a future date, so the save fails validation.  If you try to change anything in a work with an overdue embargo through Dashboard -> Works -> edit work, it also fails, but you get a flash message telling you why.

Seems like the best we can hope for is that the add fails AND a flash message tells the user why.

**Comment by chrisdaaz** [comment]
because it works when the embargo is set for a **future** date, i do not think this is a `mustfix` issue. there can be a more elegant way that the app tells you SWW, but the repository manager should be expiring embargoes on time instead of moving unexpired embargoed works into collections
