### ISSUE TITLE
Clicking delete from Collection view page throws error

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#70]
### Descriptive summary
Collection deletion works if you delete from the "Collection List View"
![screen shot 2017-09-28 at 10 00 35 am](https://user-images.githubusercontent.com/4356335/30970748-f2d59cde-a433-11e7-93fd-6239f934f169.png)

But throws error if you try to delete from "Collection View"
![screen shot 2017-09-28 at 9 58 34 am](https://user-images.githubusercontent.com/4356335/30970784-0cb79b7a-a434-11e7-9ae0-58e5d8e6ac0c.png)

### Expected behavior
Should have one way to delete OR work both places

### Steps to reproduce the behavior

1. Navigate to Dashboard: Collections
2. Click on a collection
3. Click delete
4. error

**Comment by gamontoya** [comment]
I can replicate this issue (using Firefox and Chrome).

**Comment by vantuyls** [comment]
also confirmed on Safari.

**Comment by acozine** [comment]
Here's the stacktrace:
```
I, [2017-09-29T15:45:46.029328 #3988]  INFO -- : [700a880a-fa30-4fe2-975c-169b75287fa2] Started DELETE "/collections/6q182k13s?locale=en" for 73.94.228.14 at 2017-09-29 15:45:46 +0000
F, [2017-09-29T15:45:46.030169 #3988] FATAL -- : [700a880a-fa30-4fe2-975c-169b75287fa2]   
F, [2017-09-29T15:45:46.030227 #3988] FATAL -- : [700a880a-fa30-4fe2-975c-169b75287fa2] ActionController::RoutingError (No route matches [DELETE] "/collections/6q182k13s"):
F, [2017-09-29T15:45:46.030295 #3988] FATAL -- : [700a880a-fa30-4fe2-975c-169b75287fa2]   
F, [2017-09-29T15:45:46.030365 #3988] FATAL -- : [700a880a-fa30-4fe2-975c-169b75287fa2] actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
[700a880a-fa30-4fe2-975c-169b75287fa2] actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[700a880a-fa30-4fe2-975c-169b75287fa2] railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
[700a880a-fa30-4fe2-975c-169b75287fa2] railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
[700a880a-fa30-4fe2-975c-169b75287fa2] activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[700a880a-fa30-4fe2-975c-169b75287fa2] activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
[700a880a-fa30-4fe2-975c-169b75287fa2] activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
[700a880a-fa30-4fe2-975c-169b75287fa2] railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
[700a880a-fa30-4fe2-975c-169b75287fa2] actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[700a880a-fa30-4fe2-975c-169b75287fa2] actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
[700a880a-fa30-4fe2-975c-169b75287fa2] rack (2.0.3) lib/rack/method_override.rb:22:in `call'
[700a880a-fa30-4fe2-975c-169b75287fa2] rack (2.0.3) lib/rack/runtime.rb:22:in `call'
[700a880a-fa30-4fe2-975c-169b75287fa2] activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
[700a880a-fa30-4fe2-975c-169b75287fa2] actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
[700a880a-fa30-4fe2-975c-169b75287fa2] rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
[700a880a-fa30-4fe2-975c-169b75287fa2] railties (5.1.4) lib/rails/engine.rb:522:in `call'
[700a880a-fa30-4fe2-975c-169b75287fa2] passenger (5.1.2) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
[700a880a-fa30-4fe2-975c-169b75287fa2] passenger (5.1.2) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
[700a880a-fa30-4fe2-975c-169b75287fa2] passenger (5.1.2) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
[700a880a-fa30-4fe2-975c-169b75287fa2] passenger (5.1.2) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
[700a880a-fa30-4fe2-975c-169b75287fa2] passenger (5.1.2) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by julesies** [comment]
I can't replicate this one anymore...
